### commands needed to move the robot and camera
# Topic to control arm postion
arm_joint_controller_command: "/joints_movement_node/joints_movement"

# joint states topic for arm unit
# string
arm_joint_state_topic: "/joint_states" #/joint_states

## topic names for commanding the robot base
# topic name for the base controller
# string
base_controller_topic_name: "/cmd_vel"

# Image topic
# string
#camera_image_topic: "/image_raw"  # change to topic rect
camera_image_topic: "/cam_publisher/image"

# calibration interface ID. Decides which robot's interface to use: 0 - Robotino, 1 - RAW, 2 - COB, 3 - DeKonBot
# int
calibration_ID: 3
